name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons:
  permission_handler:
  image_picker: 
  get: 
  flutter: 
    sdk: flutter
  flutter_muka: 
    path: ../

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

 