library flutter_muka;

import 'dart:async';
import 'dart:io' show HttpClient, Platform, exit;
import 'dart:typed_data';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:dio/adapter.dart';
import 'package:extended_image/extended_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_muka/views/crop_editor_helper.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:r_upgrade/r_upgrade.dart';
import 'package:scan/scan.dart';
import 'src/adapter_browser.dart' if (dart.library.js) 'package:dio/adapter_browser.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'package:dio_cookie_manager/dio_cookie_manager.dart';
import 'package:cookie_jar/cookie_jar.dart';
import 'package:flutter/services.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:flutter_muka/src/http_res.dart';
import 'package:package_info/package_info.dart';
import 'package:signature/signature.dart';
import 'model/upgrade_model/index.dart';
import 'model/dialog_share_data/index.dart';

export 'package:flutter_easyloading/flutter_easyloading.dart';
export 'package:dio/dio.dart';
export 'package:intl/intl.dart';
export 'package:path_provider/path_provider.dart';
export 'package:extended_image/extended_image.dart' show ExtendedImage, File;

part 'src/http_utils.dart';
part 'src/dialog_utils.dart';
part 'src/app_update.dart';
part 'src/utils.dart';
part 'src/verify_utils.dart';
part 'src/toast_utils.dart';
part 'src/extend_class.dart';
part 'components/list_item.dart';
part 'components/multi_image.dart';
part 'components/text_field.dart';
part 'components/code_time.dart';
part 'components/empty.dart';
part 'components/page_init.dart';
part 'components/grid_box.dart';
part 'components/grid_item.dart';
part 'components/custom_stepper.dart';
part 'components/start_up.dart';
part 'components/signature_view.dart';
part 'components/divider_text.dart';
part 'components/price_number.dart';
part 'components/round_check_box.dart';
part 'components/change_number.dart';
part 'components/easy_popup.dart';
part 'components/animated_button.dart';
part 'components/virtual_keyboard.dart';

part 'views/crop_image.dart';
part 'views/scan_page.dart';
